development:
  adapter: mysql2
  encoding: utf8
  database: testone_dev
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  database: testone_test
  username: root
  password: 

production:
  adapter: mysql2
  encoding: utf8
  database: testone_prod
  username: root
  password: 